name: Build and Push Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.manuelamm }}
          password: ${{ secrets.dckr_pat_3Y0gacftrY4T3pkidpl6GfywNWA }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ThomasShelfie/proj-thomasshelfie01:latest
